#!/usr/bin/env node
/**
 * Production packager for the Solomon Companion extension.
 *
 * The committed source tree is the DEV build (localhost origins, loadable
 * unpacked as-is). This script produces the Chrome Web Store package:
 *
 *   NR_APP_ORIGIN=https://app.example.com \
 *   NR_API_ORIGIN=https://api.example.com \
 *   node build.mjs
 *
 * (or: node build.mjs --app-origin=https://… --api-origin=https://…)
 *
 * Output: dist/prod/ (unpacked) and dist/solomon-companion-v<version>.zip.
 *
 * Transformations applied to the prod package:
 *  - config.js is rewritten with the production app/API origins
 *  - manifest content_scripts app-bridge matches -> the production app origin
 *  - manifest host_permissions: localhost entries dropped, API origin added
 *
 * The origins are REQUIRED inputs (no committed production domains): the
 * deploy domains live in the deployment environment, not this repo.
 */

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));

const COPY_FILES = [
  "background.js",
  "content.js",
  "content.css",
  "linkedin-content.js",
  "app-bridge.js",
  "popup.html",
  "popup.js",
];

function cliArg(name) {
  const prefix = `--${name}=`;
  const hit = process.argv.find((a) => a.startsWith(prefix));
  return hit ? hit.slice(prefix.length) : null;
}

function requireOrigin(name, envVar) {
  const raw = cliArg(name) || process.env[envVar] || "";
  const trimmed = raw.trim().replace(/\/+$/, "");
  if (!trimmed) {
    console.error(
      `Missing required origin: pass --${name}=https://… or set ${envVar}.`,
    );
    process.exit(1);
  }
  let parsed;
  try {
    parsed = new URL(trimmed);
  } catch {
    console.error(`Invalid ${name}: ${raw}`);
    process.exit(1);
  }
  if (parsed.protocol !== "https:" || parsed.pathname !== "/" || parsed.search || parsed.hash) {
    console.error(
      `${name} must be a bare https origin (e.g. https://app.example.com), got: ${raw}`,
    );
    process.exit(1);
  }
  return `${parsed.protocol}//${parsed.host}`;
}

const appOrigin = requireOrigin("app-origin", "NR_APP_ORIGIN");
const apiOrigin = requireOrigin("api-origin", "NR_API_ORIGIN");

const isLocalPattern = (value) =>
  value.includes("localhost") || value.includes("127.0.0.1");

const manifest = JSON.parse(
  fs.readFileSync(path.join(HERE, "manifest.json"), "utf8"),
);

manifest.host_permissions = [
  `${apiOrigin}/*`,
  ...manifest.host_permissions.filter((entry) => !isLocalPattern(entry)),
];

manifest.content_scripts = manifest.content_scripts.map((entry) => {
  if ((entry.js || []).includes("app-bridge.js")) {
    return { ...entry, matches: [`${appOrigin}/*`] };
  }
  const matches = entry.matches.filter((m) => !isLocalPattern(m));
  return { ...entry, matches };
});

const distRoot = path.join(HERE, "dist");
const outDir = path.join(distRoot, "prod");
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

for (const file of COPY_FILES) {
  fs.copyFileSync(path.join(HERE, file), path.join(outDir, file));
}
fs.cpSync(path.join(HERE, "icons"), path.join(outDir, "icons"), {
  recursive: true,
});

fs.writeFileSync(
  path.join(outDir, "manifest.json"),
  `${JSON.stringify(manifest, null, 2)}\n`,
);

fs.writeFileSync(
  path.join(outDir, "config.js"),
  [
    "// GENERATED by build.mjs — production companion defaults.",
    "var NR_DEFAULTS = {",
    `  apiUrl: ${JSON.stringify(apiOrigin)},`,
    `  appUrl: ${JSON.stringify(appOrigin)},`,
    "};",
    "",
  ].join("\n"),
);

const zipName = `solomon-companion-v${manifest.version}.zip`;
const zipPath = path.join(distRoot, zipName);
fs.rmSync(zipPath, { force: true });
let zipped = false;
try {
  execFileSync("zip", ["-r", "-q", zipPath, "."], { cwd: outDir });
  zipped = true;
} catch {
  // zip CLI unavailable — the unpacked dist/prod dir is still complete.
}

console.log(`Solomon Companion v${manifest.version} production package`);
console.log(`  app origin: ${appOrigin}`);
console.log(`  api origin: ${apiOrigin}`);
console.log(`  unpacked:   ${outDir}`);
console.log(
  zipped
    ? `  zip:        ${zipPath}`
    : `  zip:        skipped ('zip' CLI not found) — zip dist/prod manually`,
);
