#!/usr/bin/env bash
# Shared fail-closed environment for the local Gideon product-capture demo.

export NEXUSREACH_ENVIRONMENT=e2e
export NEXUSREACH_DEMO_MODE=true
export NEXUSREACH_SERVICE_ROLE=api
export NEXUSREACH_DATABASE_URL="${NEXUSREACH_DEMO_DATABASE_URL:-postgresql+asyncpg://postgres:postgres@127.0.0.1:5432/nexusreach_e2e}"
export NEXUSREACH_REDIS_URL="${NEXUSREACH_DEMO_REDIS_URL:-redis://127.0.0.1:6381/15}"
export NEXUSREACH_AUTH_MODE=dev
export NEXUSREACH_DEV_AUTH_BYPASS_ENABLED=true
export NEXUSREACH_DEV_USER_ID=00000000-0000-0000-0000-000000000001
export NEXUSREACH_DEV_USER_EMAIL=dev@nexusreach.local
export NEXUSREACH_FRONTEND_URL=http://127.0.0.1:5173
export NEXUSREACH_CORS_ORIGINS='["http://127.0.0.1:5173"]'
export NEXUSREACH_RENDERED_PAGE_FETCH_ENABLED=false
export NEXUSREACH_RENDER_REMOTE_ENABLED=false
export NEXUSREACH_EMPLOYMENT_VERIFY_ENABLED=false
export NEXUSREACH_THEORG_TRAVERSAL_ENABLED=false

# Explicit empty overrides prevent backend/.env from supplying remote services,
# paid providers, OAuth clients, or telemetry to the demo process.
for name in \
  SUPABASE_URL SUPABASE_KEY SUPABASE_JWT_SECRET SUPABASE_SERVICE_ROLE_KEY \
  APOLLO_API_KEY APOLLO_MASTER_API_KEY HUNTER_API_KEY GITHUB_TOKEN \
  JSEARCH_API_KEY ADZUNA_APP_ID ADZUNA_API_KEY DICE_API_KEY \
  USAJOBS_API_KEY USAJOBS_USER_AGENT THEMUSE_API_KEY \
  ANTHROPIC_API_KEY OPENAI_API_KEY GOOGLE_API_KEY GOOGLE_CSE_ID \
  GOOGLE_LINKEDIN_CSE_ID GROQ_API_KEY BRAVE_API_KEY SERPER_API_KEY \
  TAVILY_API_KEY YOUCOM_API_KEY EXA_API_KEY FIRECRAWL_BASE_URL \
  FIRECRAWL_API_KEY SCRAPEGRAPH_API_KEY SEARXNG_BASE_URL \
  GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET MICROSOFT_CLIENT_ID \
  MICROSOFT_CLIENT_SECRET SENTRY_DSN POSTHOG_API_KEY WAITLIST_ADMIN_TOKEN; do
  export "NEXUSREACH_${name}="
done

# A fixed synthetic-only key keeps any local model validation deterministic;
# demo fixtures never contain provider tokens and email/OAuth routes are blocked.
export NEXUSREACH_TOKEN_ENCRYPTION_PRIMARY_VERSION=v1
export NEXUSREACH_TOKEN_ENCRYPTION_KEYS='{"v1":"6nlS0wM_Tx8DqJmB1Hj3g2GJw6i1sp0S5L6XprNeWDQ="}'

export VITE_API_URL=http://127.0.0.1:8000
export VITE_AUTH_MODE=dev
export VITE_DEV_AUTH_BYPASS_ENABLED=true
export VITE_DEV_USER_EMAIL=dev@nexusreach.local
export VITE_APP_ENVIRONMENT=e2e
export VITE_DEMO_MODE=true
export VITE_ANALYTICS_ENABLED=false
export VITE_SENTRY_DSN=
export VITE_POSTHOG_KEY=
export VITE_WAITLIST_ENDPOINT=
