"""Loader for the auto-discovered ATS board registry.

The registry is generated by ``scripts/discover_ats_boards.py`` (which probes a
big seed of company names against Greenhouse/Lever/Ashby and verifies each board
against its real company name) and committed to
``app/data/discovered_ats_boards.json``. The curated-board crawl loads these on
top of the hand-curated `constants` lists, so the employer registry grows from
~160 hand-verified boards to hundreds — the "do what JobRight does" lever — while
staying fully verified and version-controlled.
"""

from __future__ import annotations

import json
import logging
from functools import lru_cache
from pathlib import Path

from app.services.jobs import constants

logger = logging.getLogger(__name__)

_DATA_PATH = Path(__file__).resolve().parents[2] / "data" / "discovered_ats_boards.json"
_SUPPORTED_ATS = frozenset({"greenhouse", "lever", "ashby"})


def _existing_registry() -> set[tuple[str, str]]:
    existing = {(b["ats"], b["slug"]) for b in constants.ATS_DISCOVER_BOARDS}
    existing |= {("lever", s) for s in constants.LEVER_DISCOVER_SLUGS}
    return existing


@lru_cache(maxsize=1)
def load_discovered_boards() -> tuple[dict[str, str], ...]:
    """Verified auto-discovered boards not already in the hand-curated registry.

    Each entry is ``{"slug", "ats", "company"}`` ready for
    ``ats.get_adapter(ats).search_board``. The ``company`` is the verified name
    captured at discovery time — the crawl stamps it on the jobs because the ATS
    board APIs sometimes return only the slug as the org name. Cached for the
    process; fails soft to ``()`` when the data file is missing or malformed (so a
    bad/absent file never breaks the crawl).
    """
    try:
        data = json.loads(_DATA_PATH.read_text())
    except (OSError, ValueError) as exc:
        logger.warning("discovered ATS boards unavailable: %s", exc)
        return ()

    existing = _existing_registry()
    seen: set[tuple[str, str]] = set()
    out: list[dict[str, str]] = []
    for board in data.get("boards", []):
        ats = board.get("ats")
        slug = board.get("slug")
        key = (ats, slug)
        if not ats or not slug or ats not in _SUPPORTED_ATS:
            continue
        if key in existing or key in seen:
            continue
        seen.add(key)
        out.append({"slug": slug, "ats": ats, "company": board.get("company") or slug})
    return tuple(out)
